//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/3/2020 6:03:38 PM
namespace NAV
{
        /// <summary>
        /// There are no comments for NAV in the schema.
        /// </summary>
    public partial class NAV : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NAV object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public NAV(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for General_Ledger_Export in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<General_Ledger_Export> General_Ledger_Export
        {
            get
            {
                if ((this._General_Ledger_Export == null))
                {
                    this._General_Ledger_Export = base.CreateQuery<General_Ledger_Export>("General_Ledger_Export");
                }
                return this._General_Ledger_Export;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<General_Ledger_Export> _General_Ledger_Export;
        /// <summary>
        /// There are no comments for General_Ledger_Export in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToGeneral_Ledger_Export(General_Ledger_Export general_Ledger_Export)
        {
            base.AddObject("General_Ledger_Export", general_Ledger_Export);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
        /// <summary>
        /// There are no comments for General_Ledger_ExportSingle in the schema.
        /// </summary>
    public partial class General_Ledger_ExportSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<General_Ledger_Export>
    {
        /// <summary>
        /// Initialize a new General_Ledger_ExportSingle object.
        /// </summary>
        public General_Ledger_ExportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new General_Ledger_ExportSingle object.
        /// </summary>
        public General_Ledger_ExportSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new General_Ledger_ExportSingle object.
        /// </summary>
        public General_Ledger_ExportSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<General_Ledger_Export> query)
            : base(query) {}

    }
        /// <summary>
        /// There are no comments for General_Ledger_Export in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Entry_No
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Entry_No")]
    public partial class General_Ledger_Export : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new General_Ledger_Export object.
        /// </summary>
        /// <param name="entry_No">Initial value of Entry_No.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static General_Ledger_Export CreateGeneral_Ledger_Export(int entry_No)
        {
            General_Ledger_Export general_Ledger_Export = new General_Ledger_Export();
            general_Ledger_Export.Entry_No = entry_No;
            return general_Ledger_Export;
        }
        /// <summary>
        /// There are no comments for Property Entry_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Entry_No
        {
            get
            {
                return this._Entry_No;
            }
            set
            {
                this.OnEntry_NoChanging(value);
                this._Entry_No = value;
                this.OnEntry_NoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Entry_No;
        partial void OnEntry_NoChanging(int value);
        partial void OnEntry_NoChanged();
        /// <summary>
        /// There are no comments for Property Posting_Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::Microsoft.OData.Edm.Date> Posting_Date
        {
            get
            {
                return this._Posting_Date;
            }
            set
            {
                this.OnPosting_DateChanging(value);
                this._Posting_Date = value;
                this.OnPosting_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.OData.Edm.Date> _Posting_Date;
        partial void OnPosting_DateChanging(global::System.Nullable<global::Microsoft.OData.Edm.Date> value);
        partial void OnPosting_DateChanged();
        /// <summary>
        /// There are no comments for Property Document_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Document_No
        {
            get
            {
                return this._Document_No;
            }
            set
            {
                this.OnDocument_NoChanging(value);
                this._Document_No = value;
                this.OnDocument_NoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Document_No;
        partial void OnDocument_NoChanging(string value);
        partial void OnDocument_NoChanged();
        /// <summary>
        /// There are no comments for Property G_L_Account_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string G_L_Account_No
        {
            get
            {
                return this._G_L_Account_No;
            }
            set
            {
                this.OnG_L_Account_NoChanging(value);
                this._G_L_Account_No = value;
                this.OnG_L_Account_NoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _G_L_Account_No;
        partial void OnG_L_Account_NoChanging(string value);
        partial void OnG_L_Account_NoChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Debit_Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<decimal> Debit_Amount
        {
            get
            {
                return this._Debit_Amount;
            }
            set
            {
                this.OnDebit_AmountChanging(value);
                this._Debit_Amount = value;
                this.OnDebit_AmountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Debit_Amount;
        partial void OnDebit_AmountChanging(global::System.Nullable<decimal> value);
        partial void OnDebit_AmountChanged();
        /// <summary>
        /// There are no comments for Property Credit_Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<decimal> Credit_Amount
        {
            get
            {
                return this._Credit_Amount;
            }
            set
            {
                this.OnCredit_AmountChanging(value);
                this._Credit_Amount = value;
                this.OnCredit_AmountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Credit_Amount;
        partial void OnCredit_AmountChanging(global::System.Nullable<decimal> value);
        partial void OnCredit_AmountChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::NAV.General_Ledger_Export as global::NAV.General_Ledger_ExportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::NAV.General_Ledger_ExportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NAV.General_Ledger_Export> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::NAV.General_Ledger_ExportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::NAV.General_Ledger_Export as global::NAV.General_Ledger_ExportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="entry_No">The value of entry_No</param>
        public static global::NAV.General_Ledger_ExportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NAV.General_Ledger_Export> _source,
            int entry_No)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Entry_No", entry_No }
            };
            return new global::NAV.General_Ledger_ExportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace NAV.ComplexTypes
{
}
